name: "Check Dependabot Alerts"
description: "Checks Open Dependabot Vulnerabilty Alerts"
author: "Craig Bath"
branding:
  icon: "alert-circle"
  color: "purple"
inputs:
  github_personal_token:
    description: "GitHub Personal Access Token"
outputs:
  total_alerts:
    description: "Total Open Dependabot Alerts"
runs:
  using: "docker"
  image: "Dockerfile"