name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Self test
        id: selftest
        uses: spicyparrot/check-dependabot@trunk        #Check out yourself to test

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.total_alerts }}" != ""
          printf ${{ steps.selftest.outputs.total_alerts }}
