name: Integration Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - uses: actions/checkout@v2
      
      - name: Self Test
        id: selftest
        uses: spicyparrot/check-dependabot@trunk        #Check out yourself to test
        with:
          token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}  

      - name: View Outputs
        run: |
          export ALERTS=${{ steps.selftest.outputs.total_alerts }}
          if [[ "$ALERTS" > 0 ]] ; then
              echo "::warn ::⚠ $ALERTS Open Vulnerabilty Alerts Found"
          else
            echo "::debug ::✅ $ALERTS Open Vulnerabilty Alerts Found"
          fi
