name: Integration Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - uses: actions/checkout@v2
      - name: Self test
        id: selftest
        uses: spicyparrot/check-dependabot@trunk        #Check out yourself to test
        with:
          github_token: ${{ github.token }}

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.total_alerts }}" != ""
          printf ${{ steps.selftest.outputs.total_alerts }}
