name: Integration Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - uses: actions/checkout@v2
      
      - name: Check Dependabot Alerts
        id: alerts
        uses: spicyparrot/check-dependabot@trunk        #Check out yourself to test
        with:
          github_personal_token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}  

      - name: View Outputs
        run: |
          export ALERTS=${{ steps.alerts.outputs.total_alerts }}
          if [[ "$ALERTS" > 0 ]] ; then
              echo "::warning ::$ALERTS Open Vulnerability Alerts Found"
          else
            echo "::debug ::✅ $ALERTS Open Vulnerability Alerts Found"
          fi
